image: node:alpine

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - build
  only:
      - master

deploy:
  stage: deploy
  script:
    - apx add lftp
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev build/ ./  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
      - master