build:
	image: node:10.15.0
	stage: build
	script:
		- npm install --progress=false
		- npm run build
	artifacts:
		expire_in: 1 week
		paths:
			- build
	only:
			- master

deploy:
	image: alpine:latest
	stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev build/ ./  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
	only:
			- master