image: node:12.10.0

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - npm prune
    - npm install --progress=false
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules
  artifacts:
    paths:
      - node_modules
  only:
    - master

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
  only:
      - master

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev build/ ./  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
      - master
